CREATE TABLE IF NOT EXISTS User(
    uID INT NOT NULL AUTO_INCREMENT,
    username  VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    isEmployee BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (uID)
);
CREATE TABLE IF NOT EXISTS Fruit(
    fID INT NOT NULL AUTO_INCREMENT, 
    Name VARCHAR(100) NOT NULL UNIQUE, 
    Price INT NOT NULL,
    PRIMARY KEY (fID)
);
CREATE TABLE IF NOT EXISTS Review(
    rID INT NOT NULL AUTO_INCREMENT,
    fID INT NOT NULL,
    uID INT NOT NULL,
    rating INT NOT NULL DEFAULT 0,
    comment VARCHAR(1000) NOT NULL,
    ratingDate DATETIME,
    PRIMARY KEY (rID),
    FOREIGN KEY (fID) REFERENCES Fruit(fID),
    FOREIGN KEY (uID) REFERENCES User(uID)
);
CREATE TABLE IF NOT EXISTS Inventory(
    iID INT NOT NULL AUTO_INCREMENT, 
    fID INT NOT NULL, 
    tStamp TIMESTAMP, 
    expirationDate DATE, 
    Amount INT DEFAULT 0,
    PRIMARY KEY (iID),
    FOREIGN KEY (fID) REFERENCES Fruit(fID)
);

CREATE TABLE IF NOT EXISTS Orders(
    oID INT NOT NULL AUTO_INCREMENT, 
    uID INT NOT NULL,
    tStamp TIMESTAMP,  
    totalPrice INT NOT NULL,
    updatedAt DATE NOT NULL,
    PRIMARY KEY (oID),
    FOREIGN KEY (uID) REFERENCES User(uID)
);
CREATE TABLE IF NOT EXISTS OrderItem(
    oiID INT NOT NULL AUTO_INCREMENT, 
    oID INT NOT NULL, 
    fID INT NOT NULL, 
    amount INT NOT NULL,
    PRIMARY KEY (oiID),
    FOREIGN KEY (oID) REFERENCES Orders(oID),
    FOREIGN KEY (fID) REFERENCES Fruit(fID)
);
CREATE TABLE IF NOT EXISTS Archive(
    oID INT NOT NULL,
    uID INT NOT NULL,
    oTimeStamp TIMESTAMP,  
    oTotalPrice INT NOT NULL,
    FOREIGN KEY (oID) REFERENCES Orders(oID),
    FOREIGN KEY (uID) REFERENCES User(uID)
);
-- testing2, Camvu trying Github
